<a href="https://colab.research.google.com/github/A-ghori/Pytorch-/blob/main/Basic_Tensor_CPU_GPU.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## What is Tensor
Tensor is a multidimmensional numerical container

See both contain numbers array but the twist pytorch tensor's has some major advantages like
- it can be run in CPU
- it can be run in GPU
- Calculate gradient easily

In [2]:
## In Numpy
import numpy as np
x = np.array([1,2,3])
x

array([1, 2, 3])

In [3]:
## In pytorch
## This is 1D tensor
import torch
x = torch.tensor([1,2,3])
print(x)
print(x.shape)
print(x.ndim)

tensor([1, 2, 3])
torch.Size([3])
1


In [4]:
## This is 2D tensor
x = torch.tensor([[1,2,3],
                  [4,5,6]])
print(x)
## this is 3D tensor
y = torch.tensor([
    [
        [1, 2],
        [3, 4]
    ],
    [
        [5, 6],
        [7, 8]
    ]
])
print(y)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


## CPU VS GPU
lower code follow this flow
x
->
CPU memory
->
PyTorch operation
->
CPU calculates

GPU = Processor that is highly useful for performing many similar numerical calculations in parallel.
- Ok what the parallel mean ??
  - it means multiple independent calculations is doin in the same time

  ```text
             CPU
              │
         calculation
              ↓
             1×10
              ↓
             2×10
              ↓
             3×10
              ↓
             4×10
              ↓
             5×10
  ```
``` text
                 GPU
                  │
       ┌──────────┼──────────┐
       ↓          ↓          ↓
     worker     worker     worker ...
       ↓          ↓          ↓
      1×10       2×10       3×10
       ↓          ↓          ↓
      result     result     result


```

```text
                 COMPUTER
                    │
          ┌─────────┴─────────┐
          ↓                   ↓
         CPU                 GPU
          │                   │
   General-purpose      Highly parallel
      processing        numerical work
          │                   │
   ┌──────┴──────┐      ┌─────┴──────────┐
   │             │      │                │
Data loading   Python  Tensor math    Matrix math
Preprocessing  Logic   Neural networks  Training
OS operations
          │                   │
          └─────────┬─────────┘
                    ↓
                  Result
```     

## CPU
→ fewer, powerful, general-purpose cores
→ many different kinds of tasks

## GPU
→ very large number of smaller compute units
→ massive parallel numerical workloads

In [5]:
x = torch.tensor([1,2,3,4,5])
x = x.to("cuda")
y = x * 10
print(x)
print(x.device)
print(y)


tensor([1, 2, 3, 4, 5], device='cuda:0')
cuda:0
tensor([10, 20, 30, 40, 50], device='cuda:0')


In [6]:
import torch

print("Pytorch Version", torch.__version__)

print('CUDA available', torch.cuda.is_available())
print('MPS available', torch.backends.mps.is_available())

if torch.backends.mps.is_available():
  device = "mps"
elif torch.cuda.is_available():
  device = "cuda"
else :
  device = "cpu"
print("Using", device)


Pytorch Version 2.11.0+cu128
CUDA available True
MPS available False
Using cuda


## Indexing

In [7]:
X = torch.tensor([
    [10,20,30],
    [40,50,60]
])
print(X[0])
print(X[1])

## Now specific Element
print(X[0][1])
# This more clearner way to write
print(X[0,1])

tensor([10, 20, 30])
tensor([40, 50, 60])
tensor(20)
tensor(20)


In [8]:
## Negative Indexing
X = torch.tensor([1,2,3,4,5,6,7,8])
print(X[-1])

tensor(8)


In [9]:
## 1D slicing
X = torch.tensor([10,20,30,40,50])
print(X[1:4]) # it follows [start:stop]
print(X[:3]) # beginig to 3 excluded
print(X[2:]) # 2 to end
print(X[::2]) # here [start:stop:step] step = 2

tensor([20, 30, 40])
tensor([10, 20, 30])
tensor([30, 40, 50])
tensor([10, 30, 50])


In [10]:
## 2D tensors

X = torch.tensor([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])

print(X.ndim)

2


In [11]:
print(X[0])
print(X[2])
print(X[1,2])

## Slice
print(X[0:2]) # row slice
print(X[:,1]) # Cols slice means ():)all rows , (1) 1st col
print(X[1:, 1:]) # X [ rows , cols ] Rows -> 1 se lekar all, Cols -> 1 se lekar all
print(X[:2, 1:3])

tensor([10, 20, 30])
tensor([70, 80, 90])
tensor(60)
tensor([[10, 20, 30],
        [40, 50, 60]])
tensor([20, 50, 80])
tensor([[50, 60],
        [80, 90]])
tensor([[20, 30],
        [50, 60]])


In [20]:
x = torch.tensor([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

print(x[0,2])
print(x[1:, :2])
print(x[1:][0:2]) ## rows + rows
print(x[:, 2])
print(x[:2, 1:3])

tensor(3)
tensor([[ 5,  6],
        [ 9, 10]])
tensor([[ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
tensor([ 3,  7, 11])
tensor([[2, 3],
        [6, 7]])
